DROP TABLE TEST_USER;
CREATE TABLE TEST_USER(
USER_ID VARCHAR(10),
USER_NAME VARCHAR(10)
);

INSERT INTO TEST_USER VALUES('1090','test1');
INSERT INTO TEST_USER VALUES('1092','test2');
INSERT INTO TEST_USER VALUES('1093','test3');

DROP TABLE TEST_USER2;
CREATE TABLE TEST_USER2(
USER_ID VARCHAR(10),
USER_NAME VARCHAR(10)
);

INSERT INTO TEST_USER2 VALUES('2090','a1');
INSERT INTO TEST_USER2 VALUES('2091','a2');
INSERT INTO TEST_USER2 VALUES('2092','a3');